# using the official Python image as base
FROM python:3.9-slim

# working directory in the container
WORKDIR /app

# copy python script and requirements.txt file into the container
COPY requirements.txt .
COPY tomtom.py .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# run the Python script
CMD ["python", "tomtom.py"]
